// Last updated: 7/27/2026, 3:00:29 PM
1class Solution {
2    public int minDepth(TreeNode root) {
3        // Base case...
4        // If the subtree is empty i.e. root is NULL, return depth as 0...
5        if(root == null)  return 0;
6        // Initialize the depth of two subtrees...
7        int leftDepth = minDepth(root.left);
8        int rightDepth = minDepth(root.right);
9        // If the both subtrees are empty...
10        if(root.left == null && root.right == null)
11            return 1;
12        // If the left subtree is empty, return the depth of right subtree after adding 1 to it...
13        if(root.left == null)
14            return 1 + rightDepth;
15        // If the right subtree is empty, return the depth of left subtree after adding 1 to it...
16        if(root.right == null)
17            return 1 + leftDepth;
18        // When the two child function return its depth...
19        // Pick the minimum out of these two subtrees and return this value after adding 1 to it...
20        return Math.min(leftDepth, rightDepth) + 1;    // Adding 1 is the current node which is the parent of the two subtrees...
21    }
22}