// Last updated: 7/27/2026, 2:59:24 PM
1class Solution {
2    public boolean isBalanced(TreeNode root) {
3        // If the tree is empty, we can say it’s balanced...
4        if (root == null)  return true;
5        // Height Function will return -1, when it’s an unbalanced tree...
6		if (Height(root) == -1)  return false;
7		return true;
8	}
9    // Create a function to return the “height” of a current subtree using recursion...
10	public int Height(TreeNode root) {
11        // Base case...
12		if (root == null)  return 0;
13        // Height of left subtree...
14		int leftHeight = Height(root.left);
15        // Height of height subtree...
16		int rightHight = Height(root.right);
17        // In case of left subtree or right subtree unbalanced, return -1...
18		if (leftHeight == -1 || rightHight == -1)  return -1;
19        // If their heights differ by more than ‘1’, return -1...
20        if (Math.abs(leftHeight - rightHight) > 1)  return -1;
21        // Otherwise, return the height of this subtree as max(leftHeight, rightHight) + 1...
22		return Math.max(leftHeight, rightHight) + 1;
23    }
24}